### ISSUE TITLE
Rigbits: Bake Spring nodes

### ISSUE THREAD

**Issue by Lohult** [mgear-dev/mgear#177] opened 2022-11-11 07:12 UTC
Problem: Baking spring chains to literal key frames. I presume the Bake Spring nodes tool was intended for this. Currently it does not function. The input prerequisite is to select at least one rig node. Selecting one or all the spring chain controls leads to the same error `mgear/latest/scripts/mgear/core/utils.py line 214: Couldn't find root node from your selection`.

I am unsure if this is a bug or a user error.

**Comment by miquelcampos** [comment] 2023-09-06 02:22
@Lohult  I can't reproduce the error but I have moved the command to animbits menu. It makes more sense
<img width="360" alt="image" src="https://github.com/mgear-dev/mgear4/assets/1050212/3bb40697-a1bb-4d01-8893-cb4cf0a736d0">
For the moment I will close the issue. I will do a release today. Please check it and see if the error persists. Please let me know

Thanks!

**Closed as completed** 2023-09-06 02:23 UTC
Labels: bug, Research/ Review
