### ISSUE TITLE
mgear viewport menu: Range Switch + missing space switch options

### ISSUE THREAD

**Issue by Lohult** [mgear-dev/mgear#178] opened 2022-11-11 08:58 UTC
Doing a range switch on any Ik/fk limb causes an error: `mgear/latest/scripts/mgear/core/anim_utils.py line 1890: 'NoneType' object has no attribute 'hasAttr' #
`
It would appear that the tool is not accounting for a namespace. As a test, removing the namespace from a rig allows the range switch tool to function.

**Comment by miquelcampos** [comment] 2023-07-26 08:46
Also found another bug where some space switch are missing in the context menu

**Comment by miquelcampos** [comment] 2023-08-08 03:10
@Lohult Hi! I know the ticket is old, but I couldn't reproduce the issue with the current mgear branch. can you reproduce the error If you take the latest commit version from the master branch?
For the moment I close this issue with the other fix that I am about to commit. 😄

**Closed as completed** 2023-08-08 03:11 UTC
Labels: bug
